/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicLayoutRouteImport } from './routes/(public)/layout'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as privateAdminLandLayoutRouteImport } from './routes/(private)/admin-land/layout'
import { Route as privatehomeLayoutRouteImport } from './routes/(private)/(home)/layout'
import { Route as publicAuthRegisterRouteImport } from './routes/(public)/auth/register'
import { Route as publicAuthLoginRouteImport } from './routes/(public)/auth/login'
import { Route as privateCreateAddressRouteImport } from './routes/(private)/create/address'
import { Route as privateAdminLandDashboardRouteImport } from './routes/(private)/admin-land/dashboard'
import { Route as privateAdminLandDevsIndexRouteImport } from './routes/(private)/admin-land/devs/index'
import { Route as privateAdminLandCompanyIndexRouteImport } from './routes/(private)/admin-land/company/index'
import { Route as privatehomeSettingsIndexRouteImport } from './routes/(private)/(home)/settings/index'
import { Route as privatehomeProfileIndexRouteImport } from './routes/(private)/(home)/profile/index'
import { Route as privatehomeFeedIndexRouteImport } from './routes/(private)/(home)/feed/index'
import { Route as privateProficiencyTestIdTestRouteImport } from './routes/(private)/proficiency-test/$id/test'
import { Route as privateProficiencyTestIdStartRouteImport } from './routes/(private)/proficiency-test/$id/start'
import { Route as privateCreateProfileDevRouteImport } from './routes/(private)/create/profile/dev'
import { Route as privateCreateProfileCompanyRouteImport } from './routes/(private)/create/profile/company'
import { Route as privateCreateProfileClientRouteImport } from './routes/(private)/create/profile/client'
import { Route as privateAdminLandDevsIdIndexRouteImport } from './routes/(private)/admin-land/devs/$id/index'
import { Route as privateAdminLandCompanyIdIndexRouteImport } from './routes/(private)/admin-land/company/$id/index'

const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicLayoutRoute,
} as any)
const privateAdminLandLayoutRoute = privateAdminLandLayoutRouteImport.update({
  id: '/(private)/admin-land',
  path: '/admin-land',
  getParentRoute: () => rootRouteImport,
} as any)
const privatehomeLayoutRoute = privatehomeLayoutRouteImport.update({
  id: '/(private)/(home)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthRegisterRoute = publicAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicAuthLoginRoute = publicAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => publicLayoutRoute,
} as any)
const privateCreateAddressRoute = privateCreateAddressRouteImport.update({
  id: '/(private)/create/address',
  path: '/create/address',
  getParentRoute: () => rootRouteImport,
} as any)
const privateAdminLandDashboardRoute =
  privateAdminLandDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => privateAdminLandLayoutRoute,
  } as any)
const privateAdminLandDevsIndexRoute =
  privateAdminLandDevsIndexRouteImport.update({
    id: '/devs/',
    path: '/devs/',
    getParentRoute: () => privateAdminLandLayoutRoute,
  } as any)
const privateAdminLandCompanyIndexRoute =
  privateAdminLandCompanyIndexRouteImport.update({
    id: '/company/',
    path: '/company/',
    getParentRoute: () => privateAdminLandLayoutRoute,
  } as any)
const privatehomeSettingsIndexRoute =
  privatehomeSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => privatehomeLayoutRoute,
  } as any)
const privatehomeProfileIndexRoute = privatehomeProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => privatehomeLayoutRoute,
} as any)
const privatehomeFeedIndexRoute = privatehomeFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => privatehomeLayoutRoute,
} as any)
const privateProficiencyTestIdTestRoute =
  privateProficiencyTestIdTestRouteImport.update({
    id: '/(private)/proficiency-test/$id/test',
    path: '/proficiency-test/$id/test',
    getParentRoute: () => rootRouteImport,
  } as any)
const privateProficiencyTestIdStartRoute =
  privateProficiencyTestIdStartRouteImport.update({
    id: '/(private)/proficiency-test/$id/start',
    path: '/proficiency-test/$id/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const privateCreateProfileDevRoute = privateCreateProfileDevRouteImport.update({
  id: '/(private)/create/profile/dev',
  path: '/create/profile/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const privateCreateProfileCompanyRoute =
  privateCreateProfileCompanyRouteImport.update({
    id: '/(private)/create/profile/company',
    path: '/create/profile/company',
    getParentRoute: () => rootRouteImport,
  } as any)
const privateCreateProfileClientRoute =
  privateCreateProfileClientRouteImport.update({
    id: '/(private)/create/profile/client',
    path: '/create/profile/client',
    getParentRoute: () => rootRouteImport,
  } as any)
const privateAdminLandDevsIdIndexRoute =
  privateAdminLandDevsIdIndexRouteImport.update({
    id: '/devs/$id/',
    path: '/devs/$id/',
    getParentRoute: () => privateAdminLandLayoutRoute,
  } as any)
const privateAdminLandCompanyIdIndexRoute =
  privateAdminLandCompanyIdIndexRouteImport.update({
    id: '/company/$id/',
    path: '/company/$id/',
    getParentRoute: () => privateAdminLandLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin-land': typeof privateAdminLandLayoutRouteWithChildren
  '/': typeof publicIndexRoute
  '/admin-land/dashboard': typeof privateAdminLandDashboardRoute
  '/create/address': typeof privateCreateAddressRoute
  '/auth/login': typeof publicAuthLoginRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/create/profile/client': typeof privateCreateProfileClientRoute
  '/create/profile/company': typeof privateCreateProfileCompanyRoute
  '/create/profile/dev': typeof privateCreateProfileDevRoute
  '/proficiency-test/$id/start': typeof privateProficiencyTestIdStartRoute
  '/proficiency-test/$id/test': typeof privateProficiencyTestIdTestRoute
  '/feed/': typeof privatehomeFeedIndexRoute
  '/profile/': typeof privatehomeProfileIndexRoute
  '/settings/': typeof privatehomeSettingsIndexRoute
  '/admin-land/company/': typeof privateAdminLandCompanyIndexRoute
  '/admin-land/devs/': typeof privateAdminLandDevsIndexRoute
  '/admin-land/company/$id/': typeof privateAdminLandCompanyIdIndexRoute
  '/admin-land/devs/$id/': typeof privateAdminLandDevsIdIndexRoute
}
export interface FileRoutesByTo {
  '/admin-land': typeof privateAdminLandLayoutRouteWithChildren
  '/': typeof publicIndexRoute
  '/admin-land/dashboard': typeof privateAdminLandDashboardRoute
  '/create/address': typeof privateCreateAddressRoute
  '/auth/login': typeof publicAuthLoginRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/create/profile/client': typeof privateCreateProfileClientRoute
  '/create/profile/company': typeof privateCreateProfileCompanyRoute
  '/create/profile/dev': typeof privateCreateProfileDevRoute
  '/proficiency-test/$id/start': typeof privateProficiencyTestIdStartRoute
  '/proficiency-test/$id/test': typeof privateProficiencyTestIdTestRoute
  '/feed': typeof privatehomeFeedIndexRoute
  '/profile': typeof privatehomeProfileIndexRoute
  '/settings': typeof privatehomeSettingsIndexRoute
  '/admin-land/company': typeof privateAdminLandCompanyIndexRoute
  '/admin-land/devs': typeof privateAdminLandDevsIndexRoute
  '/admin-land/company/$id': typeof privateAdminLandCompanyIdIndexRoute
  '/admin-land/devs/$id': typeof privateAdminLandDevsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicLayoutRouteWithChildren
  '/(private)/(home)': typeof privatehomeLayoutRouteWithChildren
  '/(private)/admin-land': typeof privateAdminLandLayoutRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(private)/admin-land/dashboard': typeof privateAdminLandDashboardRoute
  '/(private)/create/address': typeof privateCreateAddressRoute
  '/(public)/auth/login': typeof publicAuthLoginRoute
  '/(public)/auth/register': typeof publicAuthRegisterRoute
  '/(private)/create/profile/client': typeof privateCreateProfileClientRoute
  '/(private)/create/profile/company': typeof privateCreateProfileCompanyRoute
  '/(private)/create/profile/dev': typeof privateCreateProfileDevRoute
  '/(private)/proficiency-test/$id/start': typeof privateProficiencyTestIdStartRoute
  '/(private)/proficiency-test/$id/test': typeof privateProficiencyTestIdTestRoute
  '/(private)/(home)/feed/': typeof privatehomeFeedIndexRoute
  '/(private)/(home)/profile/': typeof privatehomeProfileIndexRoute
  '/(private)/(home)/settings/': typeof privatehomeSettingsIndexRoute
  '/(private)/admin-land/company/': typeof privateAdminLandCompanyIndexRoute
  '/(private)/admin-land/devs/': typeof privateAdminLandDevsIndexRoute
  '/(private)/admin-land/company/$id/': typeof privateAdminLandCompanyIdIndexRoute
  '/(private)/admin-land/devs/$id/': typeof privateAdminLandDevsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin-land'
    | '/'
    | '/admin-land/dashboard'
    | '/create/address'
    | '/auth/login'
    | '/auth/register'
    | '/create/profile/client'
    | '/create/profile/company'
    | '/create/profile/dev'
    | '/proficiency-test/$id/start'
    | '/proficiency-test/$id/test'
    | '/feed/'
    | '/profile/'
    | '/settings/'
    | '/admin-land/company/'
    | '/admin-land/devs/'
    | '/admin-land/company/$id/'
    | '/admin-land/devs/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin-land'
    | '/'
    | '/admin-land/dashboard'
    | '/create/address'
    | '/auth/login'
    | '/auth/register'
    | '/create/profile/client'
    | '/create/profile/company'
    | '/create/profile/dev'
    | '/proficiency-test/$id/start'
    | '/proficiency-test/$id/test'
    | '/feed'
    | '/profile'
    | '/settings'
    | '/admin-land/company'
    | '/admin-land/devs'
    | '/admin-land/company/$id'
    | '/admin-land/devs/$id'
  id:
    | '__root__'
    | '/(public)'
    | '/(private)/(home)'
    | '/(private)/admin-land'
    | '/(public)/'
    | '/(private)/admin-land/dashboard'
    | '/(private)/create/address'
    | '/(public)/auth/login'
    | '/(public)/auth/register'
    | '/(private)/create/profile/client'
    | '/(private)/create/profile/company'
    | '/(private)/create/profile/dev'
    | '/(private)/proficiency-test/$id/start'
    | '/(private)/proficiency-test/$id/test'
    | '/(private)/(home)/feed/'
    | '/(private)/(home)/profile/'
    | '/(private)/(home)/settings/'
    | '/(private)/admin-land/company/'
    | '/(private)/admin-land/devs/'
    | '/(private)/admin-land/company/$id/'
    | '/(private)/admin-land/devs/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
  privatehomeLayoutRoute: typeof privatehomeLayoutRouteWithChildren
  privateAdminLandLayoutRoute: typeof privateAdminLandLayoutRouteWithChildren
  privateCreateAddressRoute: typeof privateCreateAddressRoute
  privateCreateProfileClientRoute: typeof privateCreateProfileClientRoute
  privateCreateProfileCompanyRoute: typeof privateCreateProfileCompanyRoute
  privateCreateProfileDevRoute: typeof privateCreateProfileDevRoute
  privateProficiencyTestIdStartRoute: typeof privateProficiencyTestIdStartRoute
  privateProficiencyTestIdTestRoute: typeof privateProficiencyTestIdTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(private)/admin-land': {
      id: '/(private)/admin-land'
      path: '/admin-land'
      fullPath: '/admin-land'
      preLoaderRoute: typeof privateAdminLandLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/(home)': {
      id: '/(private)/(home)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privatehomeLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth/register': {
      id: '/(public)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof publicAuthRegisterRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/auth/login': {
      id: '/(public)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof publicAuthLoginRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(private)/create/address': {
      id: '/(private)/create/address'
      path: '/create/address'
      fullPath: '/create/address'
      preLoaderRoute: typeof privateCreateAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/admin-land/dashboard': {
      id: '/(private)/admin-land/dashboard'
      path: '/dashboard'
      fullPath: '/admin-land/dashboard'
      preLoaderRoute: typeof privateAdminLandDashboardRouteImport
      parentRoute: typeof privateAdminLandLayoutRoute
    }
    '/(private)/admin-land/devs/': {
      id: '/(private)/admin-land/devs/'
      path: '/devs'
      fullPath: '/admin-land/devs/'
      preLoaderRoute: typeof privateAdminLandDevsIndexRouteImport
      parentRoute: typeof privateAdminLandLayoutRoute
    }
    '/(private)/admin-land/company/': {
      id: '/(private)/admin-land/company/'
      path: '/company'
      fullPath: '/admin-land/company/'
      preLoaderRoute: typeof privateAdminLandCompanyIndexRouteImport
      parentRoute: typeof privateAdminLandLayoutRoute
    }
    '/(private)/(home)/settings/': {
      id: '/(private)/(home)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof privatehomeSettingsIndexRouteImport
      parentRoute: typeof privatehomeLayoutRoute
    }
    '/(private)/(home)/profile/': {
      id: '/(private)/(home)/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof privatehomeProfileIndexRouteImport
      parentRoute: typeof privatehomeLayoutRoute
    }
    '/(private)/(home)/feed/': {
      id: '/(private)/(home)/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof privatehomeFeedIndexRouteImport
      parentRoute: typeof privatehomeLayoutRoute
    }
    '/(private)/proficiency-test/$id/test': {
      id: '/(private)/proficiency-test/$id/test'
      path: '/proficiency-test/$id/test'
      fullPath: '/proficiency-test/$id/test'
      preLoaderRoute: typeof privateProficiencyTestIdTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/proficiency-test/$id/start': {
      id: '/(private)/proficiency-test/$id/start'
      path: '/proficiency-test/$id/start'
      fullPath: '/proficiency-test/$id/start'
      preLoaderRoute: typeof privateProficiencyTestIdStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/create/profile/dev': {
      id: '/(private)/create/profile/dev'
      path: '/create/profile/dev'
      fullPath: '/create/profile/dev'
      preLoaderRoute: typeof privateCreateProfileDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/create/profile/company': {
      id: '/(private)/create/profile/company'
      path: '/create/profile/company'
      fullPath: '/create/profile/company'
      preLoaderRoute: typeof privateCreateProfileCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/create/profile/client': {
      id: '/(private)/create/profile/client'
      path: '/create/profile/client'
      fullPath: '/create/profile/client'
      preLoaderRoute: typeof privateCreateProfileClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/admin-land/devs/$id/': {
      id: '/(private)/admin-land/devs/$id/'
      path: '/devs/$id'
      fullPath: '/admin-land/devs/$id/'
      preLoaderRoute: typeof privateAdminLandDevsIdIndexRouteImport
      parentRoute: typeof privateAdminLandLayoutRoute
    }
    '/(private)/admin-land/company/$id/': {
      id: '/(private)/admin-land/company/$id/'
      path: '/company/$id'
      fullPath: '/admin-land/company/$id/'
      preLoaderRoute: typeof privateAdminLandCompanyIdIndexRouteImport
      parentRoute: typeof privateAdminLandLayoutRoute
    }
  }
}

interface publicLayoutRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicAuthLoginRoute: typeof publicAuthLoginRoute
  publicAuthRegisterRoute: typeof publicAuthRegisterRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicAuthLoginRoute: publicAuthLoginRoute,
  publicAuthRegisterRoute: publicAuthRegisterRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

interface privatehomeLayoutRouteChildren {
  privatehomeFeedIndexRoute: typeof privatehomeFeedIndexRoute
  privatehomeProfileIndexRoute: typeof privatehomeProfileIndexRoute
  privatehomeSettingsIndexRoute: typeof privatehomeSettingsIndexRoute
}

const privatehomeLayoutRouteChildren: privatehomeLayoutRouteChildren = {
  privatehomeFeedIndexRoute: privatehomeFeedIndexRoute,
  privatehomeProfileIndexRoute: privatehomeProfileIndexRoute,
  privatehomeSettingsIndexRoute: privatehomeSettingsIndexRoute,
}

const privatehomeLayoutRouteWithChildren =
  privatehomeLayoutRoute._addFileChildren(privatehomeLayoutRouteChildren)

interface privateAdminLandLayoutRouteChildren {
  privateAdminLandDashboardRoute: typeof privateAdminLandDashboardRoute
  privateAdminLandCompanyIndexRoute: typeof privateAdminLandCompanyIndexRoute
  privateAdminLandDevsIndexRoute: typeof privateAdminLandDevsIndexRoute
  privateAdminLandCompanyIdIndexRoute: typeof privateAdminLandCompanyIdIndexRoute
  privateAdminLandDevsIdIndexRoute: typeof privateAdminLandDevsIdIndexRoute
}

const privateAdminLandLayoutRouteChildren: privateAdminLandLayoutRouteChildren =
  {
    privateAdminLandDashboardRoute: privateAdminLandDashboardRoute,
    privateAdminLandCompanyIndexRoute: privateAdminLandCompanyIndexRoute,
    privateAdminLandDevsIndexRoute: privateAdminLandDevsIndexRoute,
    privateAdminLandCompanyIdIndexRoute: privateAdminLandCompanyIdIndexRoute,
    privateAdminLandDevsIdIndexRoute: privateAdminLandDevsIdIndexRoute,
  }

const privateAdminLandLayoutRouteWithChildren =
  privateAdminLandLayoutRoute._addFileChildren(
    privateAdminLandLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  publicLayoutRoute: publicLayoutRouteWithChildren,
  privatehomeLayoutRoute: privatehomeLayoutRouteWithChildren,
  privateAdminLandLayoutRoute: privateAdminLandLayoutRouteWithChildren,
  privateCreateAddressRoute: privateCreateAddressRoute,
  privateCreateProfileClientRoute: privateCreateProfileClientRoute,
  privateCreateProfileCompanyRoute: privateCreateProfileCompanyRoute,
  privateCreateProfileDevRoute: privateCreateProfileDevRoute,
  privateProficiencyTestIdStartRoute: privateProficiencyTestIdStartRoute,
  privateProficiencyTestIdTestRoute: privateProficiencyTestIdTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
