/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicLayoutRouteImport } from './routes/(public)/layout'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicAuthRegisterRouteImport } from './routes/(public)/auth/register'
import { Route as publicAuthLoginRouteImport } from './routes/(public)/auth/login'
import { Route as privateHomeDevRouteImport } from './routes/(private)/home/dev'
import { Route as privateCreateAddressRouteImport } from './routes/(private)/create/address'
import { Route as privateCreateProfileDevRouteImport } from './routes/(private)/create/profile/dev'
import { Route as privateCreateProfileCompanyRouteImport } from './routes/(private)/create/profile/company'
import { Route as privateCreateProfileClientRouteImport } from './routes/(private)/create/profile/client'

const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicAuthRegisterRoute = publicAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicAuthLoginRoute = publicAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => publicLayoutRoute,
} as any)
const privateHomeDevRoute = privateHomeDevRouteImport.update({
  id: '/(private)/home/dev',
  path: '/home/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const privateCreateAddressRoute = privateCreateAddressRouteImport.update({
  id: '/(private)/create/address',
  path: '/create/address',
  getParentRoute: () => rootRouteImport,
} as any)
const privateCreateProfileDevRoute = privateCreateProfileDevRouteImport.update({
  id: '/(private)/create/profile/dev',
  path: '/create/profile/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const privateCreateProfileCompanyRoute =
  privateCreateProfileCompanyRouteImport.update({
    id: '/(private)/create/profile/company',
    path: '/create/profile/company',
    getParentRoute: () => rootRouteImport,
  } as any)
const privateCreateProfileClientRoute =
  privateCreateProfileClientRouteImport.update({
    id: '/(private)/create/profile/client',
    path: '/create/profile/client',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/create/address': typeof privateCreateAddressRoute
  '/home/dev': typeof privateHomeDevRoute
  '/auth/login': typeof publicAuthLoginRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/create/profile/client': typeof privateCreateProfileClientRoute
  '/create/profile/company': typeof privateCreateProfileCompanyRoute
  '/create/profile/dev': typeof privateCreateProfileDevRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/create/address': typeof privateCreateAddressRoute
  '/home/dev': typeof privateHomeDevRoute
  '/auth/login': typeof publicAuthLoginRoute
  '/auth/register': typeof publicAuthRegisterRoute
  '/create/profile/client': typeof privateCreateProfileClientRoute
  '/create/profile/company': typeof privateCreateProfileCompanyRoute
  '/create/profile/dev': typeof privateCreateProfileDevRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicLayoutRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(private)/create/address': typeof privateCreateAddressRoute
  '/(private)/home/dev': typeof privateHomeDevRoute
  '/(public)/auth/login': typeof publicAuthLoginRoute
  '/(public)/auth/register': typeof publicAuthRegisterRoute
  '/(private)/create/profile/client': typeof privateCreateProfileClientRoute
  '/(private)/create/profile/company': typeof privateCreateProfileCompanyRoute
  '/(private)/create/profile/dev': typeof privateCreateProfileDevRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create/address'
    | '/home/dev'
    | '/auth/login'
    | '/auth/register'
    | '/create/profile/client'
    | '/create/profile/company'
    | '/create/profile/dev'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create/address'
    | '/home/dev'
    | '/auth/login'
    | '/auth/register'
    | '/create/profile/client'
    | '/create/profile/company'
    | '/create/profile/dev'
  id:
    | '__root__'
    | '/(public)'
    | '/(public)/'
    | '/(private)/create/address'
    | '/(private)/home/dev'
    | '/(public)/auth/login'
    | '/(public)/auth/register'
    | '/(private)/create/profile/client'
    | '/(private)/create/profile/company'
    | '/(private)/create/profile/dev'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
  privateCreateAddressRoute: typeof privateCreateAddressRoute
  privateHomeDevRoute: typeof privateHomeDevRoute
  privateCreateProfileClientRoute: typeof privateCreateProfileClientRoute
  privateCreateProfileCompanyRoute: typeof privateCreateProfileCompanyRoute
  privateCreateProfileDevRoute: typeof privateCreateProfileDevRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/auth/register': {
      id: '/(public)/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof publicAuthRegisterRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/auth/login': {
      id: '/(public)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof publicAuthLoginRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(private)/home/dev': {
      id: '/(private)/home/dev'
      path: '/home/dev'
      fullPath: '/home/dev'
      preLoaderRoute: typeof privateHomeDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/create/address': {
      id: '/(private)/create/address'
      path: '/create/address'
      fullPath: '/create/address'
      preLoaderRoute: typeof privateCreateAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/create/profile/dev': {
      id: '/(private)/create/profile/dev'
      path: '/create/profile/dev'
      fullPath: '/create/profile/dev'
      preLoaderRoute: typeof privateCreateProfileDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/create/profile/company': {
      id: '/(private)/create/profile/company'
      path: '/create/profile/company'
      fullPath: '/create/profile/company'
      preLoaderRoute: typeof privateCreateProfileCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/create/profile/client': {
      id: '/(private)/create/profile/client'
      path: '/create/profile/client'
      fullPath: '/create/profile/client'
      preLoaderRoute: typeof privateCreateProfileClientRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface publicLayoutRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicAuthLoginRoute: typeof publicAuthLoginRoute
  publicAuthRegisterRoute: typeof publicAuthRegisterRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicAuthLoginRoute: publicAuthLoginRoute,
  publicAuthRegisterRoute: publicAuthRegisterRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicLayoutRoute: publicLayoutRouteWithChildren,
  privateCreateAddressRoute: privateCreateAddressRoute,
  privateHomeDevRoute: privateHomeDevRoute,
  privateCreateProfileClientRoute: privateCreateProfileClientRoute,
  privateCreateProfileCompanyRoute: privateCreateProfileCompanyRoute,
  privateCreateProfileDevRoute: privateCreateProfileDevRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
